CREATE TABLE EMPLOYEE (
  FNAME VARCHAR(20),
  MINIT VARCHAR(1),
  LNAME VARCHAR(20),
  SSN NUMBER(10),
  BDATE date,
  ADDRESS VARCHAR(50),
  SEX VARCHAR(1),
  SALARY NUMBER(10),
  SUPERSSN NUMBER(10),
  DNO NUMBER(10),
  PRIMARY KEY(SSN)
);

DESC EMPLOYEE;

CREATE TABLE DEPARTMENT(
DNAME VARCHAR(20),
DNUMBER NUMBER(10) PRIMARY KEY,
MGRSSN NUMBER(10),
MGRSTARTDATE date,
FOREIGN KEY (MGRSSN) REFERENCES EMPLOYEE(SSN)
);

DESC DEPARTMENT;

CREATE TABLE DEPT_LOCATIONS(
DNUMBER NUMBER(10),
DLOCATION VARCHAR(20),
FOREIGN KEY(DNUMBER) REFERENCES DEPARTMENT(DNUMBER)
);
DESC DEPT_LOCATIONS;

CREATE TABLE PROJECT(
PNAME VARCHAR(20),
PNUMBER NUMBER(10),
PLOCATION VARCHAR(20),
DNUM NUMBER(10),
PRIMARY KEY(PNUMBER),
FOREIGN KEY(DNUM) REFERENCES DEPARTMENT(DNUMBER)
);

DESC PROJECT;

CREATE TABLE WORKS_ON (
ESSN NUMBER(10),
PNO NUMBER(10),
HOURS NUMBER(10) DEFAULT NULL,
FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN),
FOREIGN KEY (PNO) REFERENCES PROJECT(PNUMBER)
);

DESC WORKS_ON;

CREATE TABLE DEPENDENT(
ESSN NUMBER(10),
DEPENDENT_NAME VARCHAR(20),
SEX VARCHAR(1),
BDATE date,
RELATIONSHIP VARCHAR(20),
FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN)
);

DESC DEPENDENT;

INSERT INTO EMPLOYEE VALUES ('John','B','Smith',123456789,'09-JAN-1995','731 Fondren,Houston,TX','M',30000,333445555,5);
INSERT INTO EMPLOYEE VALUES('Alicia','J','Zelaya',999887777,'19-JUL-1951','3321 Castle,Spring,TX','F',25000,987654321,4);
INSERT INTO EMPLOYEE VALUES('Jennifer','S','Wallace',987654321,'20-JUN-1941','291 Berry,bellaire,TX','F',43000,888665555,4);
INSERT INTO EMPLOYEE VALUES('Ramesh','K','Narayan',666884444,'15-SEP-1962','975 Fire Oak,Humble,TX','M',38000,333445555,5);
INSERT INTO EMPLOYEE VALUES('Joyce','A','Bond',453453453,'31-JUL-1963','5631 Rice,Houston,TX','F',25000,333445555,5);
INSERT INTO EMPLOYEE VALUES('Ahmad','V','Jabbar',333445555,'29-MAR-1969','980 Dallas,Houston,TX','M',25000,987654321,4);
INSERT INTO EMPLOYEE VALUES('James','E','Bong',888665555,'10-NOV-1956','450 Stone,Houston,TX','M',55000,987654321,1);
SELECT * FROM EMPLOYEE;

INSERT INTO DEPARTMENT VALUES('Research',5,333445555,'22-MAY-1988');
INSERT INTO DEPARTMENT VALUES('Administration',4,987654321,'1-JAN-1995');
INSERT INTO DEPARTMENT VALUES('Headquarters',1,888665555,'19-JUN-1981');
SELECT * FROM DEPARTMENT;

INSERT INTO DEPT_LOCATIONS VALUES(1,'Houston');
INSERT INTO DEPT_LOCATIONS VALUES(4,'Stafford');
INSERT INTO DEPT_LOCATIONS VALUES(5,'Bellaire');
INSERT INTO DEPT_LOCATIONS VALUES(5,'Sugarland');

SELECT * FROM DEPT_LOCATIONS;

INSERT INTO PROJECT VALUES ('ProductX',1,'Bellaire',5);
INSERT INTO PROJECT VALUES ('ProductY',2,'Sugarland',5);
INSERT INTO PROJECT VALUES ('ProductZ',3,'Houston',5);
INSERT INTO PROJECT VALUES ('Computerization',10,'Stafford',4);
INSERT INTO PROJECT VALUES ('Reorganization',20,'Houston',1);
INSERT INTO PROJECT VALUES ('Newbenefits',30,'Stafford',4);

SELECT * FROM PROJECT;

INSERT INTO WORKS_ON VALUES (123456789,1,32.5);
INSERT INTO WORKS_ON VALUES(123456789,2,7.5);
INSERT INTO WORKS_ON VALUES(666884444,3,40.0);
INSERT INTO WORKS_ON VALUES(453453453,1,20.0);
INSERT INTO WORKS_ON VALUES(453453453,2,20.0);
INSERT INTO WORKS_ON VALUES(333445555,2,10.0);
INSERT INTO WORKS_ON VALUES(333445555,3,10.0);
INSERT INTO WORKS_ON VALUES(333445555,10,10.0);
INSERT INTO WORKS_ON VALUES(333445555,20,10.0);
INSERT INTO WORKS_ON VALUES(999887777,30,30.0);
INSERT INTO WORKS_ON VALUES(999887777,10,10.0);
INSERT INTO WORKS_ON VALUES(666884444,10,35.0);
INSERT INTO WORKS_ON VALUES(666884444,30,5.0);
INSERT INTO WORKS_ON VALUES(987654321,30,20.0);
INSERT INTO WORKS_ON VALUES(987654321,20,15.0);
SELECT * FROM WORKS_ON;

INSERT INTO DEPENDENT VALUES (999887777,'Alice','F','5-APR-1986','DAUGHTER');
INSERT INTO DEPENDENT VALUES(666884444,'Theodore','M','25-OCT-1983','SON');
INSERT INTO DEPENDENT VALUES(453453453,'Joy','F','3-MAY-1958','SPOUSE');
INSERT INTO DEPENDENT VALUES(987654321,'Abner','M','28-FEB-1942','SPOUSE');
INSERT INTO DEPENDENT VALUES(123456789,'Michael','M','4-JAN-1988','SON');
INSERT INTO DEPENDENT VALUES(123456789,'Alice','F','30-DEC-1988','DAUGHTER');
INSERT INTO DEPENDENT VALUES(123456789,'Elizabeth','F','5-MAY-1967','SPOUSE');
SELECT * FROM DEPENDENT;






-- 1. For every project in 'Stafford', list the project number, controlling department, and manager details.
SELECT P.PNUMBER, P.DNUM, E.LNAME, E.ADDRESS, E.BDATE
FROM PROJECT P
JOIN DEPARTMENT D ON P.DNUM = D.DNUMBER
JOIN EMPLOYEE E ON D.MGRSSN = E.SSN
WHERE P.PLOCATION = 'Stafford';

-- 2. Retrieve employees who work on all projects controlled by department 5.
SELECT E.FNAME, E.LNAME
FROM EMPLOYEE E
WHERE NOT EXISTS (
    SELECT P.PNUMBER FROM PROJECT P
    WHERE P.DNUM = 5 
    EXCEPT
    SELECT W.PNO FROM WORKS_ON W
    WHERE W.ESSN = E.SSN
);

-- 3. List all project numbers involving 'Smith' as a worker or a manager.
SELECT DISTINCT P.PNUMBER
FROM PROJECT P
JOIN DEPARTMENT D ON P.DNUM = D.DNUMBER
JOIN EMPLOYEE M ON D.MGRSSN = M.SSN
LEFT JOIN WORKS_ON W ON P.PNUMBER = W.PNO
LEFT JOIN EMPLOYEE E ON W.ESSN = E.SSN
WHERE E.LNAME = 'Smith' OR M.LNAME = 'Smith';

-- 4. Retrieve employees who have no dependents.
SELECT E.FNAME, E.LNAME
FROM EMPLOYEE E
WHERE NOT EXISTS (
    SELECT 1 FROM DEPENDENT D WHERE D.ESSN = E.SSN
);

-- 5. List managers who have at least one dependent.
SELECT DISTINCT E.FNAME, E.LNAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.SSN = D.MGRSSN
JOIN DEPENDENT DEP ON E.SSN = DEP.ESSN;

-- 6. Retrieve employee names and their supervisors’ names.
SELECT E.FNAME AS Employee_FName, E.LNAME AS Employee_LName,
       S.FNAME AS Supervisor_FName, S.LNAME AS Supervisor_LName
FROM EMPLOYEE E
LEFT JOIN EMPLOYEE S ON E.SUPERSSN = S.SSN;

-- 7. Show new salaries with a 10% raise for those working on 'ProductX'.
SELECT E.FNAME, E.LNAME, E.SALARY * 1.10 AS New_Salary
FROM EMPLOYEE E
JOIN WORKS_ON W ON E.SSN = W.ESSN
JOIN PROJECT P ON W.PNO = P.PNUMBER
WHERE P.PNAME = 'ProductX';

-- 8. List employees and projects they work on, ordered by department and name.
SELECT E.FNAME, E.LNAME, P.PNAME
FROM EMPLOYEE E
JOIN WORKS_ON W ON E.SSN = W.ESSN
JOIN PROJECT P ON W.PNO = P.PNUMBER
ORDER BY E.DNO, E.LNAME, E.FNAME;

-- 9. Retrieve employees who do not have supervisors.
SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE SUPERSSN IS NULL;

-- 10. Employees with a dependent having the same last name.
SELECT DISTINCT E.FNAME, E.LNAME
FROM EMPLOYEE E
JOIN DEPENDENT D ON E.SSN = D.ESSN
WHERE E.LNAME = D.DEPENDENT_NAME;

-- 11. Retrieve SSNs of employees working on project numbers 1 or 2.
SELECT DISTINCT ESSN
FROM WORKS_ON
WHERE PNO IN (1, 2);

-- 12. Employees with a salary greater than all employees in department 5.
SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE SALARY > ALL (
    SELECT SALARY FROM EMPLOYEE WHERE DNO = 5
);

-- 13. Salary statistics (SUM, MAX, MIN, AVG).
SELECT SUM(SALARY) AS Total_Salary, MAX(SALARY) AS Max_Salary,
       MIN(SALARY) AS Min_Salary, AVG(SALARY) AS Avg_Salary
FROM EMPLOYEE;

-- 14. Salary statistics for 'Research' department.
SELECT SUM(E.SALARY) AS Total_Salary, MAX(E.SALARY) AS Max_Salary,
       MIN(E.SALARY) AS Min_Salary, AVG(E.SALARY) AS Avg_Salary
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DNO = D.DNUMBER
WHERE D.DNAME = 'Research';

-- 15. Employees with two or more dependents.
SELECT E.FNAME, E.LNAME
FROM EMPLOYEE E
JOIN DEPENDENT D ON E.SSN = D.ESSN
GROUP BY E.SSN, E.FNAME, E.LNAME
HAVING COUNT(D.DEPENDENT_NAME) >= 2;

-- 16. Count employees earning > 40,000 per department (only if department has > 5 employees).
SELECT E.DNO, COUNT(*) AS Employee_Count
FROM EMPLOYEE E
WHERE E.SALARY > 40000
GROUP BY E.DNO
HAVING COUNT(*) > 5;

-- 17. Number of employees working on each project.
SELECT P.PNUMBER, P.PNAME, COUNT(W.ESSN) AS Employee_Count
FROM PROJECT P
LEFT JOIN WORKS_ON W ON P.PNUMBER = W.PNO
GROUP BY P.PNUMBER, P.PNAME;

-- 18. Projects with more than two employees working.
SELECT P.PNUMBER, P.PNAME, COUNT(W.ESSN) AS Employee_Count
FROM PROJECT P
JOIN WORKS_ON W ON P.PNUMBER = W.PNO
GROUP BY P.PNUMBER, P.PNAME
HAVING COUNT(W.ESSN) > 2;

-- 19. Employees from department 5 working on each project.
SELECT P.PNUMBER, P.PNAME, COUNT(W.ESSN) AS Employee_Count
FROM PROJECT P
JOIN WORKS_ON W ON P.PNUMBER = W.PNO
JOIN EMPLOYEE E ON W.ESSN = E.SSN
WHERE E.DNO = 5
GROUP BY P.PNUMBER, P.PNAME;

-- 20. Departments with > 5 employees and count of employees earning > 40,000.
SELECT DNO, COUNT(*) AS Employee_Count
FROM EMPLOYEE
WHERE SALARY > 40000
GROUP BY DNO
HAVING COUNT(*) > 5;
